import { Link, useForm } from '@inertiajs/react';
import Layout, { EmptyState, FieldError, PageHeader, buttonClass, inputClass, panelClass } from '../../components/Layout';
import { engagePath } from '../../lib/engagePath';

export default function Index({ workspace, events, automations }) {
    const form = useForm({ name: '', trigger_event_id: events[0]?.id ?? '', reentry_policy: 'every_time' });
    const submit = (e) => { e.preventDefault(); form.post(engagePath('automations')); };
    return <Layout title="Automations" workspace={workspace}><PageHeader eyebrow="Journeys" title="Automations" description="Turn customer activity into timely, multi-step messages." />
        <section className={panelClass}><h2 className="font-semibold">Create an automation</h2><form onSubmit={submit} className="mt-5 grid gap-4 lg:grid-cols-[1.4fr_1fr_1fr_auto] lg:items-end"><Field label="Name"><input className={inputClass} value={form.data.name} onChange={e => form.setData('name', e.target.value)} placeholder="Welcome sequence" /><FieldError message={form.errors.name} /></Field><Field label="Trigger event"><select className={inputClass} value={form.data.trigger_event_id} onChange={e => form.setData('trigger_event_id', e.target.value)}><option value="">Select an event</option>{events.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><FieldError message={form.errors.trigger_event_id} /></Field><Field label="Re-entry"><select className={inputClass} value={form.data.reentry_policy} onChange={e => form.setData('reentry_policy', e.target.value)}><option value="every_time">Every event</option><option value="one_active_run_per_person">One active run</option><option value="once_ever_per_person">Once per person</option></select></Field><button className={buttonClass} disabled={form.processing || !events.length}>Create draft</button></form>{!events.length && <p className="mt-3 text-xs text-amber-200">Create an event before starting an automation.</p>}</section>
        <section className={`${panelClass} mt-6`}><div className="flex items-center justify-between"><h2 className="font-semibold">All automations</h2><span className="text-xs text-slate-500">{automations.length} total</span></div><div className="mt-4 divide-y divide-white/[0.07]">{automations.length === 0 ? <EmptyState title="No automations yet" description="Create an event, then build your first customer journey." /> : automations.map(x => <Link key={x.id} href={engagePath(`automations/${x.id}`)} className="flex items-center justify-between gap-4 py-4 hover:text-emerald-300"><div><div className="font-medium">{x.name}</div><div className="mt-1 text-xs text-slate-500">Triggered by {x.trigger_event?.name} · {x.reentry_policy.replaceAll('_', ' ')} · {x.runs_count} runs</div></div><span className={`rounded-full px-2.5 py-1 text-xs ${x.status === 'active' ? 'bg-emerald-400/10 text-emerald-300' : 'bg-amber-400/10 text-amber-200'}`}>{x.status}</span></Link>)}</div></section>
    </Layout>;
}
function Field({ label, children }) { return <label className="block text-xs font-medium uppercase tracking-wider text-slate-400">{label}{children}</label>; }
